# Generated by Django 5.2.2 on 2026-01-23 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='documentflow.department', verbose_name='Отдел'),
            preserve_default=False,
        ),
    ]
