# Generated by Django 5.2.2 on 2026-01-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='approval_order',
            field=models.CharField(choices=[('sequential', 'Последовательный'), ('parallel', 'Параллельный')], default='sequential', max_length=20, verbose_name='Порядок согласования'),
        ),
    ]
