# Generated by Django 5.2.2 on 2026-01-24 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0004_user_middle_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['step__step_number', 'created_at'], 'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
        migrations.AlterModelOptions(
            name='documentroutestep',
            options={'ordering': ['step_number'], 'verbose_name': 'Этап маршрута', 'verbose_name_plural': 'Этапы маршрута'},
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentroutestep',
            unique_together={('template', 'step_number')},
        ),
        migrations.AddField(
            model_name='documentroutestep',
            name='approval_rule',
            field=models.CharField(choices=[('all', 'Все должны согласовать'), ('any', 'Достаточно одного')], default='all', max_length=20, verbose_name='Правило согласования'),
        ),
        migrations.AddField(
            model_name='documentroutestep',
            name='execution_mode',
            field=models.CharField(choices=[('sequential', 'Последовательно'), ('parallel', 'Параллельно')], default='sequential', max_length=20, verbose_name='Тип выполнения этапа'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='documentflow.documentroutestep', verbose_name='Этап маршрута'),
        ),
        migrations.AlterField(
            model_name='documentroutestep',
            name='step_number',
            field=models.PositiveIntegerField(verbose_name='Номер этапа'),
        ),
        migrations.AlterField(
            model_name='documentroutestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documentflow.documentroutetemplate', verbose_name='Шаблон маршрута'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'step', 'approver')},
        ),
        migrations.RemoveField(
            model_name='documentroutestep',
            name='department',
        ),
        migrations.RemoveField(
            model_name='documentroutestep',
            name='user',
        ),
        migrations.CreateModel(
            name='DocumentRouteStepApprover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvers', to='documentflow.documentroutestep', verbose_name='Этап маршрута')),
                ('user', models.ForeignKey(limit_choices_to={'status': 'working'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Согласующий')),
            ],
            options={
                'verbose_name': 'Согласующий этапа',
                'verbose_name_plural': 'Согласующие этапа',
                'unique_together': {('step', 'user')},
            },
        ),
    ]
