# Generated by Django 5.2.2 on 2026-01-24 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0005_alter_approval_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approval',
            options={'ordering': ['step', 'created_at'], 'verbose_name': 'Согласование', 'verbose_name_plural': 'Согласования'},
        ),
        migrations.AlterModelOptions(
            name='documentroutestep',
            options={'ordering': ['step_number']},
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='documentroutestep',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentroutestep',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentflow.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='documentroutestep',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='step',
            field=models.PositiveIntegerField(default=1, verbose_name='Шаг согласования'),
        ),
        migrations.AlterField(
            model_name='documentroutestep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='documentroutestep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='documentflow.documentroutetemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'approver', 'step')},
        ),
        migrations.DeleteModel(
            name='DocumentRouteStepApprover',
        ),
        migrations.RemoveField(
            model_name='documentroutestep',
            name='approval_rule',
        ),
        migrations.RemoveField(
            model_name='documentroutestep',
            name='execution_mode',
        ),
    ]
