# Generated by Django 5.2.2 on 2026-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0006_alter_approval_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentroutetemplate',
            name='approval_order',
            field=models.CharField(choices=[('sequential', 'Последовательный'), ('parallel', 'Параллельный')], default='sequential', max_length=20, verbose_name='Порядок согласования'),
        ),
    ]
