# Generated by Django 5.2.2 on 2026-01-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0007_documentroutetemplate_approval_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='action_type',
            field=models.CharField(choices=[('approve', 'Согласование'), ('acknowledge', 'Ознакомление'), ('execute', 'Исполнение')], default='approve', max_length=20, verbose_name='Тип обработки'),
        ),
        migrations.AlterField(
            model_name='approval',
            name='decision',
            field=models.CharField(choices=[('pending', 'Ожидает решения'), ('approved', 'Согласовано'), ('rejected', 'Отклонено'), ('returned', 'Возвращено на доработку'), ('acknowledged', 'Ознакомлен'), ('executed', 'Исполнен')], default='pending', max_length=20, verbose_name='Решение'),
        ),
    ]
