# Generated by Django 5.2.2 on 2026-01-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0008_document_action_type_alter_approval_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_rejection_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_rejection_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к отклонению'),
        ),
    ]
