# Generated by Django 5.2.2 on 2026-01-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0009_document_last_rejection_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approval',
            name='cycle',
            field=models.PositiveIntegerField(default=1, verbose_name='Раунд согласования'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('document', 'approver', 'step', 'cycle')},
        ),
    ]
