# Generated by Django 5.2.2 on 2026-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0010_alter_approval_unique_together_approval_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='approval_order',
            field=models.CharField(choices=[('sequential', 'Последовательный'), ('parallel', 'Параллельный')], default='sequential', max_length=20, verbose_name='Порядок согласования'),
        ),
        migrations.AddField(
            model_name='document',
            name='manual_route',
            field=models.JSONField(blank=True, null=True, verbose_name='Ручной маршрут'),
        ),
    ]
