# Generated by Django 4.2.7 on 2026-01-30 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentflow', '0016_replacement_end_date_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replacement',
            name='reason',
            field=models.CharField(choices=[('vacation', 'Отпуск'), ('sick', 'Больничный'), ('business_trip', 'Командировка'), ('maternity', 'Декрет'), ('idle', 'Простой'), ('dismissed', 'Уволен'), ('other', 'Другое')], default='vacation', max_length=50, verbose_name='Причина замены'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('vacation', 'В отпуске'), ('sick', 'На больничном'), ('business_trip', 'В командировке'), ('maternity', 'В декрете'), ('idle', 'В простое'), ('other', 'Другое'), ('dismissed', 'Уволен')], default='working', max_length=20, verbose_name='Статус сотрудника'),
        ),
    ]
